created_by:
  default: ''
  name: created_by
  native: true
  required: false
  use_default_if_nonexistent: false
description:
  default: ''
  name: description
  native: true
  required: true
  use_default_if_nonexistent: false
embargo_until:
  default: ''
  name: embargo_until
  native: true
  required: false
  use_default_if_nonexistent: false
end_time:
  default: ''
  name: end_time
  native: true
  required: false
  use_default_if_nonexistent: false
groups:
  default: ''
  name: groups
  native: true
  required: false
  use_default_if_nonexistent: false
identifiers:
  default: ''
  name: identifiers
  native: true
  required: false
  use_default_if_nonexistent: false
institution:
  default: ''
  name: institution
  native: true
  required: false
  use_default_if_nonexistent: false
metadata:
  default: ''
  name: metadata
  native: true
  required: false
  use_default_if_nonexistent: false
name:
  default: ''
  name: name
  native: true
  required: true
  use_default_if_nonexistent: false
object_schema:
  default: ''
  name: object_schema
  native: true
  required: false
  use_default_if_nonexistent: false
principal_investigator:
  default: ''
  name: principal_investigator
  native: true
  required: true
  use_default_if_nonexistent: false
start_time:
  default: ''
  name: start_time
  native: true
  required: false
  use_default_if_nonexistent: false
url:
  default: ''
  name: url
  native: true
  required: false
  use_default_if_nonexistent: false
users:
  default: ''
  name: users
  native: true
  required: false
  use_default_if_nonexistent: false
