---
repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
    - id: pylint
      stages: [commit]
      name: pylint
      entry: pylint
      language: python
      args: [src]
      additional_dependencies:
        - PyYAML
        - backoff
        - requests
        - pydantic
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    - id: mypy
      stages: [commit]
      additional_dependencies:
        - types-requests
        - types-PyYAML
        - types-mock
        - pydantic
      exclude: tests, docs
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
    - id: python-bandit-vulnerability-check
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      stages: [commit]
      language: python
      additional_dependencies:
        - pytest
        - responses
        - mock
        - backoff
        - PyYAML
        - pydantic
        - devtools
      entry: pytest -v src
      types: [python]
      pass_filenames: false
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
    -   id: python-safety-dependencies-check
