---
repos:
-   repo: https://github.com/rcmdnk/pyproject-pre-commit
    rev: v0.0.26
    hooks:
    - id: black
    - id: isort
    - id: bandit
    - id: mypy
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.0
    hooks:
    - id: pylint
      stages: [commit]
      name: pylint
      entry: pylint
      language: python
      args: [src]
      additional_dependencies:
        - typer
        - rocrate
        - PyYAML
        - backoff
        - requests
        - pydantic
        - python-slugify
        - validators
        - pydantic-settings
        - typer
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      stages: [pre-push]
      language: python
      additional_dependencies:
        - pytest
        - responses
        - mock
        - backoff
        - PyYAML
        - pydantic
        - devtools
        - pydantic-settings
        - validators
        - pytz
        - python-slugify
        - python-dateutil
      entry: pytest -v tests
      types: [python]
      pass_filenames: false
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
    -   id: python-safety-dependencies-check
-   repo: local
    hooks:
     -   id: wily
         stages: [pre-push]
         name: wily
         entry: wily diff
         verbose: true
         language: python
         additional_dependencies: [wily]
