---
repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/pylint
    rev: v2.17.5
    hooks:
    - id: pylint
      stages: [commit]
      name: pylint
      entry: pylint
      language: python
      args: [src]
      additional_dependencies:
        - PyYAML
        - backoff
        - requests
        - pydantic
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    - id: mypy
      stages: [commit]
      additional_dependencies:
        - types-requests
        - types-PyYAML
        - types-mock
        - pydantic
      exclude: tests, docs
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      stages: [pre-push]
      args:
       - configfile
       - pyproject.toml
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      stages: [pre-push]
      language: python
      additional_dependencies:
        - pytest
        - responses
        - mock
        - backoff
        - PyYAML
        - pydantic
        - devtools
        - pydantic-settings
        - validators
        - pytz
        - python-slugify
        - python-dateutil
      entry: pytest -v tests
      types: [python]
      pass_filenames: false
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
    -   id: python-safety-dependencies-check
-   repo: local
    hooks:
     -   id: wily
         stages: [pre-push]
         name: wily
         entry: wily diff
         verbose: true
         language: python
         additional_dependencies: [wily]
