[tool.poetry]
name = "mytardis_ingestion"
version = "0.2.0"
description = ""
authors = ["Chris Seal <c.seal@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"
backoff = "^2.1.2"
PyYAML = "^6.0"
python-decouple = "^3.6"
types-PyYAML = "^6.0.11"
pydantic = "^1.10.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
mock = "^4.0.3"
pytest-dependency = "^0.5.1"
pylint = "^2.15.3"
interrogate = "^1.5.0"
mypy = "^0.971"
types-requests = "^2.28.10"
types-mock = "^4.0.11"
PySnooper = "^1.1.0"
responses = "^0.21.0"
pre-commit = "^2.18.1"
bandit = "^1.7.4"
pytest-cov = "^3.0.0"
genbadge = {extras = ["tests", "coverage"], version = "^1.0.6"}
click = "8.1.3"
coverage = {extras = ["toml"], version = "^6.3.2"}
pyright = "^1.1.254"
devtools = "^0.8.0"

[tool.isort]
profile = "black"

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
exclude = ["tests", "docs", "build"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*", "^test$"]
verbose = 2
quiet = false
whitelist-regex = []
color = true
fail-under = 50

[tool.mypy]
mypy_path = [
	  "^src$"
	  ]
ignore_missing_imports = true
exclude = [
       "^tests/.*$",
       "^docs/.*$",
       ]
plugins = ["pydantic.mypy"]

[tool.bandit]
exclude_dirs = [
       	     "tests",
       	     "docs",
       	     ]

[tool.coverage.run]
omit = [
     "tests/*",
     "docs/*",
     "src/specific_implementations/*",
     "src/helpers/*"
     ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
