[tool.poetry]
name = "mytardis_ingestion"
version = "0.2.0"
description = ""
authors = ["Chris Seal <c.seal@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"
backoff = "^1.11.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
mock = "^4.0.3"
pytest-dependency = "^0.5.1"
pylint = "^2.12.2"
interrogate = "^1.5.0"
mypy = "^0.931"
types-requests = "^2.27.11"
types-mock = "^4.0.11"

[tool.isort]
profile = "black"

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
exclude = ["mytardis_ingestion/tests", "mytardis_ingestion/docs", "build"]
gnore-regex = ["^get$", "^mock_.*", ".*BaseClass.*", "^test$"]
verbose = 2
quiet = false
whitelist-regex = []
color = true
generate-badge = "."
badge-format = "svg"
fail-under = 50

[tool.mypy]
exclude = [
	'^mytardis_ingestion\/docs\/*',
	]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
