---
# Project template. Please replace <key> with the metadata keys defined in the schema and <value> with its value
#
# Necessary info
project_name: <value>
project_ids:
  - <a list of identifiers that are used for this object>
  - <a list of identifiers that are used for this object>
description: <value>
lead_researcher: <value>
# schema: <value> - un-comment if multiple schema have been defined and set the appropriate type of schema
#
# Access control. Please remove or comment out un-necessary types of group/users
# Groups are preferred over individual users for the purposes of admin
#
# TODO Update the ACL model
#
# General metadata
#
metadata:
  <key>: <value>
  <key>: <value>
