name: Test and Lint MyTardis Ingestion

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

    - name: Set Poetry config
      run: |
        poetry config settings.virtualenvs.in-project false
        poetry config settings.virtualenvs.path ~/.virtualenvs

    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Run pytest
      run: PYTHONPATH=src/ poetry run python -m pytest -v --cov=src/ tests/

    - name: Run Coverage
      run: PYTHONPATH=src/ poetry run python -m coverage report -m;

    - name: Generate XML Report
      run: PYTHONPATH=src/ poetry run python -m coverage xml
