name: Test and Lint MyTardis Ingestion

on:
  pull_request:
    branches:
      - main
  # Run on main every day at 5am-ish (expressed in UTC time here)
  schedule:
      - cron: '0 16 * * *'
  # Allow manual triggering through GitHub
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Run pytest
      run: PYTHONPATH=src/ poetry run python -m pytest -v --cov=src/ tests/

    - name: Run Coverage
      run: PYTHONPATH=src/ poetry run python -m coverage report -m;

    - name: Generate XML Report
      run: PYTHONPATH=src/ poetry run python -m coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Run pylint
      run: PYTHONPATH=src/ poetry run python -m pylint src/ --rcfile .pylintrc

    - name: Run mypy
      # Takes configuration from pyproject.toml
      run: PYTHONPATH=src/ poetry run python -m mypy

    - name: Check import formatting with isort
      run: PYTHONPATH=src/ poetry run python -m python -m isort --check --diff --profile black src

    - name: Check code formatting with Black
      run: PYTHONPATH=src/ poetry run python -m black --check --diff src
