name: Test and Lint MyTardis Ingestion

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Run pytest
      run: PYTHONPATH=src/ poetry run python -m pytest -v --cov=src/ tests/

    - name: Run Coverage
      run: PYTHONPATH=src/ poetry run python -m coverage report -m;

    - name: Generate XML Report
      run: PYTHONPATH=src/ poetry run python -m coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
